### ISSUE TITLE
Собрать бота с Джангой

### ISSUE THREAD

**Issue by iPROJEKT** [Studio-Yandex-Practicum-Hackathons/culture_its_ok_3#13]
Собрать бота с Джангой

**Comment by Tepesh-Vlad** [comment]
на данный момент есть соединени6е бота с БД, но не через отдельное приложение, а через manager команды

**Comment by Tepesh-Vlad** [comment]
получается выбирать маршрут и ходить по нему

**Comment by Tepesh-Vlad** [comment]
На демо была демонстрация:
выбираем маршрут
ходим по маршруту
пишем комментарии
