### ISSUE TITLE
Доработка бота

### ISSUE THREAD

**Issue by iPROJEKT** [Studio-Yandex-Practicum-Hackathons/culture_its_ok_3#25]
- Добавить кнопки в бота 
- Поставить ограничения при выборе номеров для новых экспонатов в новых маршрутах
- задание со звездочкой - для демонстрации заказчику сделать 4й маршрут со всеми вау-возможностями (звук, видео и т д ).

**Comment by Kostin-ES** [comment]
Добавлены кнопки от 1 до 10 после каждого объекта.
Добавлена ссылка для маленьких людей.
Изменения в ветке dockers.
